// <auto-generated />
using System;
using Media.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Media.Database.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20250312163655_ConfigValues")]
    partial class ConfigValues
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("Media.Database.Entity.ApiCacheEntry", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<double>("ValidityInSeconds")
                        .HasColumnType("REAL");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("ApiCacheEntries");
                });

            modelBuilder.Entity("Media.Database.Entity.FolderBookmark", b =>
                {
                    b.Property<string>("Path")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Path");

                    b.ToTable("FolderBookmarks");
                });

            modelBuilder.Entity("Media.Database.Entity.Metadata", b =>
                {
                    b.Property<string>("Path")
                        .HasColumnType("TEXT");

                    b.Property<string>("Album")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Artist")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Codecs")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<uint>("DiscNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("PlayTimeInSeconds")
                        .HasColumnType("REAL");

                    b.Property<long>("Size")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<uint>("TrackNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VideoHeight")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VideoWidth")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Path");

                    b.HasIndex("Album");

                    b.HasIndex("Artist");

                    b.HasIndex("Genre");

                    b.HasIndex("Size");

                    b.HasIndex("Year");

                    b.ToTable("Metadata");
                });

            modelBuilder.Entity("Media.Database.Entity.PlayedEntry", b =>
                {
                    b.Property<string>("Path")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastPlayed")
                        .HasColumnType("TEXT");

                    b.Property<string>("MetadataPath")
                        .HasColumnType("TEXT");

                    b.HasKey("Path");

                    b.HasIndex("MetadataPath");

                    b.ToTable("PlayedEntries");
                });

            modelBuilder.Entity("Media.Database.Entity.Setting", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("Media.Database.Entity.PlayedEntry", b =>
                {
                    b.HasOne("Media.Database.Entity.Metadata", "Metadata")
                        .WithMany()
                        .HasForeignKey("MetadataPath");

                    b.Navigation("Metadata");
                });
#pragma warning restore 612, 618
        }
    }
}
